### ISSUE TITLE
label-maker labels raising a tilepie.reader.InvalidFormatError

### ISSUE THREAD

**Issue by dropmeaword** [developmentseed/label-maker#111]
Hi all,

Thanks a lot for releasing this software. I am trying to use your toolkit to conduct my own research using satellite imagery. But unfortunately I am hitting a wall when I try.

I am running python 3.6.6 on pyenv (I noticed that label-maker doesn't seem to work on python 2.7) and I have installed label-maker using the procedure you explain here: http://devseed.com/label-maker/

Using the sample `config.json` you suggest in your documentation I then run `label-maker download`, this seems to create a valid sqlite3 mbtiles file on ~/data, all fine so far. After that I try to run `label-maker labels` and that fails with the following error message:

```
label-maker labels
Retiling QA Tiles to zoom level 12 (takes a bit)
tippecanoe-decode: invalid option -- 'c'
Usage: tippecanoe-decode file.mbtiles zoom x y
tippecanoe: invalid option -- '-'
Usage: tippecanoe -o out.mbtiles [-n name] [-l layername] [-z maxzoom] [-Z minzoom] [-B basezoom] [-d detail] [-D lower-detail] [-m min-detail] [-x excluded-field ...] [-y included-field ...] [-X] [-r droprate] [-b buffer] [-t tmpdir] [-a rco] [-p sfkld] [-q] [-P] [file.json ...]
Determining labels for each tile
Traceback (most recent call last):
  File "/home/zilog/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tilepie/reader.py", line 42, in _query
    self._cur.execute(sql, *args)
sqlite3.OperationalError: no such table: tiles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zilog/.pyenv/versions/3.6.6/bin/label-maker", line 11, in <module>
    load_entry_point('label-maker==0.4.0', 'console_scripts', 'label-maker')()
  File "/home/zilog/.pyenv/versions/3.6.6/lib/python3.6/site-packages/label_maker/main.py", line 84, in cli
    make_labels(dest_folder=dest_folder, sparse=sparse, **config)
  File "/home/zilog/.pyenv/versions/3.6.6/lib/python3.6/site-packages/label_maker/label.py", line 85, in make_labels
    _mapper, _callback, _done)
  File "/home/zilog/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tilepie/__init__.py", line 26, in tilereduce
    tilecontent = uncompress(tm.tile(tile[0], tile[1], tile[2]))
  File "/home/zilog/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tilepie/reader.py", line 60, in tile
    WHERE zoom_level=? AND tile_column=? AND tile_row=?;''', (z, x, tms_y))
  File "/home/zilog/.pyenv/versions/3.6.6/lib/python3.6/site-packages/tilepie/reader.py", line 44, in _query
    raise InvalidFormatError(("%s while reading %s") % (e, self.filename))
tilepie.reader.InvalidFormatError: no such table: tiles while reading data/togo-z12.mbtiles```

It seems like there are several things going on here, so I am not sure how to move on forward with this. Any help is much appreciated.

**Comment by drewbo** [comment]
Hi @dropmeaword, thanks for the report. This part of the code is a little clunky because we make OS calls. What operating system are you using and which version of `tippecanoe` do you have installed?
