### ISSUE TITLE
@rpath error on download

### ISSUE THREAD

**Issue by mapninja** [developmentseed/label-maker#143]
Anyone have advice on this error when I run label-maker download?

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/label-maker", line 6, in <module>
    from label_maker.main import cli
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/label_maker/main.py", line 13, in <module>
    from label_maker.download import download_mbtiles
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/label_maker/download.py", line 6, in <module>
    from homura import download
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homura.py", line 8, in <module>
    import pycurl
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pycurl.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libssh2.1.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pycurl.cpython-36m-darwin.so
  Reason: image not found
```

Something to do with dynamic linking. I'm reading up on how Conda and Homebrew hose each other's links, but it's all greek to me.

**Comment by drewbo** [comment]
Maybe `conda install libssh2 `?
