### ISSUE TITLE
Pycurl error

### ISSUE THREAD

**Issue by DeepVoltaire** [developmentseed/label-maker#151]
Hi, thanks for the repository! I created a completely new conda environment on Ubuntu, installed only label-maker and now are getting this error when calling label-maker in cli: 

```
Traceback (most recent call last):
  File "/home/philip/anaconda3/envs/label_maker/bin/label-maker", line 5, in <module>
    from label_maker.main import cli
  File "/home/philip/anaconda3/envs/label_maker/lib/python3.6/site-packages/label_maker/main.py", line 13, in <module>
    from label_maker.download import download_mbtiles
  File "/home/philip/anaconda3/envs/label_maker/lib/python3.6/site-packages/label_maker/download.py", line 6, in <module>
    from homura import download
  File "/home/philip/anaconda3/envs/label_maker/lib/python3.6/site-packages/homura.py", line 8, in <module>
    import pycurl
ImportError: /home/philip/anaconda3/envs/label_maker/lib/python3.6/site-packages/pycurl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: CRYPTO_set_locking_callback
```

Any pointers? I tried upgrading the pycurl version, but then it shows:
`ImportError: pycurl: libcurl link-time version (7.58.0) is older than compile-time version (7.60.0)`

Thanks!

**Comment by DeepVoltaire** [comment]
I solved it by doing `conda install pycurl` after pip installing label-maker.
