### ISSUE TITLE
syntax error while running label-maker download --dest togo --config config.json?

### ISSUE THREAD

**Issue by PallawiSinghal** [developmentseed/label-maker#155]
when I run the command **label-maker download --dest togo --config config.json**
**I get the following error?**
Traceback (most recent call last):
  File "/usr/local/bin/label-maker", line 11, in <module>
    load_entry_point('label-maker==0.6.1', 'console_scripts', 'label-maker')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/label_maker/main.py", line 14, in <module>
    from label_maker.label import make_labels
  File "/usr/local/lib/python2.7/dist-packages/label_maker/label.py", line 96
    for tile in tiles(*bounding_box, [zoom]):
**SyntaxError: only named arguments may follow expression**

**my config file contains:**
{
  "country": "togo",
  "bounding_box": [1.09725, 6.05520, 1.34582, 6.30915],
  "zoom": 12,
  "classes": [
    { "name": "Roads", "filter": ["has", "highway"] },
    { "name": "Buildings", "filter": ["has", "building"] }
  ],
  "imagery": "http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=pk.eyJ1IjoicGFsbG3owYzBqMv_lpWOWAUUV47kU7CQ",
  "background_ratio": 1,
  "ml_type": "classification"
}

**Comment by drewbo** [comment]
@PallawiSinghal it looks like you're using python 2.7 but only 3.6+ is supported

**Comment by PallawiSinghal** [comment]
(venv) pallawi@pallawi-Nitro-AN715-51:~/my_new_project$ label-maker download --dest ./data/ --config config.json
Traceback (most recent call last):
 
**Thank you. I changed that and it worked
Now when I run the above command I get the following error:
Can you please help. I have almost spent 3 days but I am not able to run this.**

 File "/home/pallawi/my_new_project/venv/bin/label-maker", line 7, in <module>
    from label_maker.main import cli
  File "/home/pallawi/my_new_project/venv/lib/python3.6/site-packages/label_maker/main.py", line 14, in <module>
    from label_maker.label import make_labels
  File "/home/pallawi/my_new_project/venv/lib/python3.6/site-packages/label_maker/label.py", line 22, in <module>
    from label_maker.utils import class_match
ImportError: cannot import name 'class_match'

**Comment by PallawiSinghal** [comment]
Finally I did it. yeeeee.
Just wrote
**from label_maker.utils import *** 
and it worked.

**Comment by ramyaragupathy** [comment]
@drewbo - I'm still seeing this error: 

`from label_maker.utils import class_match
ImportError: cannot import name 'class_match'`

Did you update the files under lib directly @PallawiSinghal - even that threw the same error for me specifically for get_image function

**Comment by Rub21** [comment]
@ramyaragupathy Maybe you could use label-maker from the docker container: https://github.com/developmentseed/docker-label-maker it works fine for me.
