### ISSUE TITLE
Error installing six 1.4.1

### ISSUE THREAD

**Issue by Rub21** [developmentseed/label-maker#26]
In my computer, I use python 2.7, I've installed python  3 using `brew`  and I've set up `alias python=python3` in my `~/. basrc` . however, it throws  👇  an error:

```
vir $ pip install label-maker
Collecting label-maker
Collecting mapbox-vector-tile==1.2.0 (from label-maker)
Collecting olefile==0.44 (from label-maker)
Collecting Pillow==4.3.0 (from label-maker)
  Using cached Pillow-4.3.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy==1.13.3 (from label-maker)
  Using cached numpy-1.13.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyclipper==1.0.6 (from label-maker)
  Using cached pyclipper-1.0.6-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting Shapely==1.6.3 (from label-maker)
  Using cached Shapely-1.6.3-cp27-cp27m-macosx_10_9_intel.macosx_10_9_x86_64.whl
Collecting pycurl==7.43.0.1 (from label-maker)
Collecting rasterio==1.0a12 (from label-maker)
  Using cached rasterio-1.0a12-cp27-cp27m-macosx_10_9_intel.macosx_10_9_x86_64.whl
Collecting six==1.10.0 (from label-maker)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting mercantile==1.0.0 (from label-maker)
  Using cached mercantile-1.0.0-py2-none-any.whl
Collecting pyproj==1.9.5.1 (from label-maker)
Requirement already satisfied: geojson==2.3.0 in /Library/Python/2.7/site-packages (from label-maker)
Requirement already satisfied: click==6.7 in /Library/Python/2.7/site-packages (from label-maker)
Requirement already satisfied: Cerberus==1.1 in /Library/Python/2.7/site-packages (from label-maker)
Collecting tilepie==0.2.1 (from label-maker)
  Using cached tilepie-0.2.1-py2.py3-none-any.whl
Collecting protobuf==3.5.0.post1 (from label-maker)
  Using cached protobuf-3.5.0.post1-py2.py3-none-any.whl
Collecting requests==2.11.0 (from label-maker)
  Using cached requests-2.11.0-py2.py3-none-any.whl
Requirement already satisfied: humanize==0.5.1 in /Library/Python/2.7/site-packages (from label-maker)
Collecting mbutil==0.3.0 (from label-maker)
  Using cached mbutil-0.3.0-py2.py3-none-any.whl
Collecting homura==0.1.5 (from label-maker)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from mapbox-vector-tile==1.2.0->label-maker)
Collecting future (from mapbox-vector-tile==1.2.0->label-maker)
Requirement already satisfied: affine in /Library/Python/2.7/site-packages (from rasterio==1.0a12->label-maker)
Requirement already satisfied: snuggs>=1.4.1 in /Library/Python/2.7/site-packages (from rasterio==1.0a12->label-maker)
Requirement already satisfied: enum34 in /Library/Python/2.7/site-packages (from rasterio==1.0a12->label-maker)
Collecting attrs (from rasterio==1.0a12->label-maker)
  Using cached attrs-17.4.0-py2.py3-none-any.whl
Requirement already satisfied: click-plugins in /Library/Python/2.7/site-packages (from rasterio==1.0a12->label-maker)
Requirement already satisfied: cligj in /Library/Python/2.7/site-packages (from rasterio==1.0a12->label-maker)
Requirement already satisfied: certifi in /Library/Python/2.7/site-packages (from homura==0.1.5->label-maker)
Requirement already satisfied: pyparsing in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from snuggs>=1.4.1->rasterio==1.0a12->label-maker)
Installing collected packages: six, protobuf, future, Shapely, pyclipper, mapbox-vector-tile, olefile, Pillow, numpy, pycurl, attrs, rasterio, mercantile, pyproj, tilepie, requests, mbutil, homura, label-maker
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/6v/__4yg2p950382cycwndc2cf80000gn/T/pip-23SqDP-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by giswqs** [comment]
Have you tried [Anaconda](https://www.anaconda.com/download/?lang=en-us#linux)? Install Anaconda and then create a Python environment using the command `conda create -n py36 python=3.6`. Then `source activate py36` and `pip install label-maker`

You also need to install [tippecanoe](https://github.com/mapbox/tippecanoe) using the following commands:

- git clone https://github.com/mapbox/tippecanoe.git
- sudo apt-get install build-essential libsqlite3-dev zlib1g-dev
- make
- sudo make install

**Comment by Geoyi** [comment]
@Rub21, @wronk has an instruction for [`set up your python-environment`](https://gist.github.com/wronk/a902185f5f8ed018263d828e1027009b) and it's by far the best pyenv setup I've ever tried, you might wanna give a try too. @giswqs's option sounds pretty good too, but I found Anaconda has much-limited package options, I will avoid using Anaconda if I could.

**Comment by wronk** [comment]
Closing this as it's likely a python environment issue. @Rub21, let us know if you run into more problems down the line though.
