### ISSUE TITLE
Is resnet.py intended to work with the example configuration?

### ISSUE THREAD

**Issue by tmcw** [developmentseed/label-maker#69]
Running through the README verbatim and using the `togo` configuration successfully produces `data.npz`, but running the `resnet.py` example with that data produces this error:

```
~/p/maps〉python3 resnet.py
Using TensorFlow backend.
x_train shape: (8, 256, 256, 3)
8 train samples
3 test samples
class_weight {0: 1, 1: 0.0}
2018-04-13 10:58:18.219381: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "resnet.py", line 83, in <module>
    workers=4)
  File "/usr/local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 2160, in fit_generator
    val_x, val_y, val_sample_weight)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1480, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected fc1000 to have shape (2,) but got array with shape (3,)
```

I'm not sure whether resnet.py is _intended_ to work with the `togo` configuration. If not that, is there a configuration that produces data that works with `resnet.py`?

**Comment by drewbo** [comment]
@tmcw the example resnet was written to work with [this example](https://github.com/developmentseed/label-maker/blob/master/examples/walkthrough-classification-aws.md). The example configuration creates one extra class (which would be my guess as to what specifically causes the error). Should we add a note around this somewhere in the docs?

**Comment by tmcw** [comment]
Closing per the other one - no longer working with that particularly observable-related usecase!
