### ISSUE TITLE
error happend when use "pip install label_maker"

### ISSUE THREAD

**Issue by 1126876778** [developmentseed/label-maker#87]
rasterio/_base.c(522): fatal error C1083: 无法打开包括文件: “cpl_conv.h”: No such file or directory

**Comment by drewbo** [comment]
Hi @1126876778, can you provide more information about your operating system and install method? It looks like `rasterio` didn't install correctly

**Comment by 1126876778** [comment]
I use win10 system and python 3.6 .when I use command "pip install rasterio==1.0a12" ,it have same error message.but when I use "pip install rasterio" can install success。But The version cannot be used in label_maker .

**Comment by drewbo** [comment]
@1126876778 I'm not sure how to resolve but [this thread](https://github.com/mapbox/rasterio/issues/603) might provide some other ideas

**Comment by yjykitty** [comment]
Same problem here with windows 7 and python 3.5. I can install rasterio successfully with anaconda but the setup always uninstall the current installed packages.

**Comment by Geoyi** [comment]
@yjykitty, you might want to set up a [python development environment](https://gist.github.com/wronk/a902185f5f8ed018263d828e1027009b) instead of using anaconda for this particular task.

**Comment by yjykitty** [comment]
@Geoyi Yeah I'm already in the python environment if that's what you mean? There's a `(py36)` in front of `C:\Users\username`. I mean when I do `pip install label_maker`, although I've already have the resterio installed, it will always uninstall it and try to install it again, and this part will raise the  “cpl_conv.h”: No such file or directory.

**Comment by Geoyi** [comment]
oh, i see what you meant @yjykitty. This error might come from one of Rasterio's dependencies, python-rasterstats, which I've seen before. Can you do `pip install --pre "rasterio>=1.0a12"` instead, it will install the resterio with pre-compiled binary wheels.

**Comment by 1126876778** [comment]
I have try all the solution but do not solve the question.

**Comment by drewbo** [comment]
@1126876778 we released a temporary version of `label-maker` (`0.3.3`) which has a looser `rasterio` version requirement which should make the install easier. Can you try reinstalling `rasterio>1` and then installing the latest `label-maker`?

**Comment by JimmyGao0204** [comment]
When I install label maker on Windows 10, some errors happened. The specific errors are showed below.
Using cached https://files.pythonhosted.org/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: nad2bin.c
    nad2bin.c(129): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
    nad2bin.c(130): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
    nad2bin.c(137): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
    nad2bin.c(138): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
    nad2bin.c(352): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
    nad2bin.c(353): warning C4244: “=”: 从“double”转换到“float”，可能丢失数据
    pj_malloc.c
    LINK : fatal error LNK1104: 无法打开文件“kernel32.lib”
    using bundled proj4..
    Traceback (most recent call last):
      File "c:\python36\lib\distutils\_msvccompiler.py", line 519, in link
        self.spawn([self.linker] + ld_args)
      File "c:\python36\lib\distutils\_msvccompiler.py", line 542, in spawn
        return super().spawn(cmd)
      File "c:\python36\lib\distutils\ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "c:\python36\lib\distutils\spawn.py", line 38, in spawn
        _spawn_nt(cmd, search_path, dry_run=dry_run)
      File "c:\python36\lib\distutils\spawn.py", line 81, in _spawn_nt
        "command %r failed with exit status %d" % (cmd, rc))
    distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1104
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\belon\AppData\Local\Temp\pip-install-n0qyhkth\pyproj\setup.py", line 74, in <module>
        cc.link_executable(objects, execname, extra_postargs = [ '/MANIFEST' ] if os.name == 'nt' else  None)
      File "c:\python36\lib\distutils\ccompiler.py", line 734, in link_executable
        debug, extra_preargs, extra_postargs, None, target_lang)
      File "c:\python36\lib\distutils\_msvccompiler.py", line 522, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1104
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\belon\AppData\Local\Temp\pip-install-n0qyhkth\pyproj\

**Comment by chenxin95** [comment]
python@ubuntu:~$ label-maker
Traceback (most recent call last):
  File "/usr/local/bin/label-maker", line 11, in <module>
    load_entry_point('label-maker==0.5.1', 'console_scripts', 'label-maker')()
  File "/usr/local/lib/python3.6/site-packages/label_maker/main.py", line 69, in cli
    logger.setLevel(args.pop('log') * 10)
KeyError: 'log'
